services:
  postgres:
    image: postgres:16.1@sha256:09f23e02d76670d3b346a3c00aa33a27cf57aab8341eedfcdaed41459d14f5c4
    env_file:
      - .env
    ports:
      - '${DOCKER_DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: $DOCKER_DATABASE_NAME
      POSTGRES_USER: $DOCKER_DATABASE_USERNAME
      POSTGRES_PASSWORD: $DOCKER_DATABASE_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DOCKER_DATABASE_NAME']
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1@sha256:d0ebf65280da2e1b1491d1b93648281afd353d4b9ea19160090303cec9a233bd
    profiles:
      - observability
    env_file:
      - .env
    command: ['--config=/etc/otelcol-contrib/config.yml']
    ports:
      - '${DOCKER_OTEL_COLLECTOR_PORT:-4318}:4318'
    volumes:
      - ./docker/otel/collector.yml:/etc/otelcol-contrib/config.yml:ro
