/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ManagerWorkspacesIndexRouteImport } from './routes/manager/workspaces/index'
import { Route as ManagerUsersIndexRouteImport } from './routes/manager/users/index'
import { Route as ManagerDashboardIndexRouteImport } from './routes/manager/dashboard.index'
import { Route as ManagerAccountIndexRouteImport } from './routes/manager/account.index'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify.index'
import { Route as LoginErrorIndexRouteImport } from './routes/login/error.index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account.index'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks.resend'
import { Route as ApiTelemetrySentryTunnelRouteImport } from './routes/api/telemetry.sentry-tunnel'
import { Route as ApiTelemetryLogsRouteImport } from './routes/api/telemetry.logs'
import { Route as ApiCronWeeklyReportsRouteImport } from './routes/api/cron.weekly-reports'
import { Route as ApiCronDailyIngestRouteImport } from './routes/api/cron.daily-ingest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ManagerWorkspacesIdIndexRouteImport } from './routes/manager/workspaces/$id.index'
import { Route as ManagerUsersNewIndexRouteImport } from './routes/manager/users/new.index'
import { Route as ManagerUsersIdIndexRouteImport } from './routes/manager/users/$id.index'
import { Route as AppSourcesSourceIdIndexRouteImport } from './routes/app/sources/$sourceId.index'
import { Route as AppReportsReportIdIndexRouteImport } from './routes/app/reports/$reportId.index'
import { Route as ApiProvidersProviderCallbackRouteImport } from './routes/api/providers.$provider.callback'
import { Route as ApiDevEmailTemplateRouteImport } from './routes/api/dev.email.$template'
import { Route as ManagerUsersIdUpdateIndexRouteImport } from './routes/manager/users/$id.update.index'
import { Route as ApiTelemetryOtelV1TracesRouteImport } from './routes/api/telemetry.otel.v1.traces'
import { Route as ApiTelemetryOtelV1MetricsRouteImport } from './routes/api/telemetry.otel.v1.metrics'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ManagerWorkspacesIndexRoute = ManagerWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerUsersIndexRoute = ManagerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerDashboardIndexRoute = ManagerDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAccountIndexRoute = ManagerAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginErrorIndexRoute = LoginErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetrySentryTunnelRoute =
  ApiTelemetrySentryTunnelRouteImport.update({
    id: '/api/telemetry/sentry-tunnel',
    path: '/api/telemetry/sentry-tunnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryLogsRoute = ApiTelemetryLogsRouteImport.update({
  id: '/api/telemetry/logs',
  path: '/api/telemetry/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWeeklyReportsRoute = ApiCronWeeklyReportsRouteImport.update({
  id: '/api/cron/weekly-reports',
  path: '/api/cron/weekly-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyIngestRoute = ApiCronDailyIngestRouteImport.update({
  id: '/api/cron/daily-ingest',
  path: '/api/cron/daily-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerWorkspacesIdIndexRoute =
  ManagerWorkspacesIdIndexRouteImport.update({
    id: '/workspaces/$id/',
    path: '/workspaces/$id/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerUsersNewIndexRoute = ManagerUsersNewIndexRouteImport.update({
  id: '/users/new/',
  path: '/users/new/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerUsersIdIndexRoute = ManagerUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AppSourcesSourceIdIndexRoute = AppSourcesSourceIdIndexRouteImport.update({
  id: '/sources/$sourceId/',
  path: '/sources/$sourceId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsReportIdIndexRoute = AppReportsReportIdIndexRouteImport.update({
  id: '/reports/$reportId/',
  path: '/reports/$reportId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiProvidersProviderCallbackRoute =
  ApiProvidersProviderCallbackRouteImport.update({
    id: '/api/providers/$provider/callback',
    path: '/api/providers/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevEmailTemplateRoute = ApiDevEmailTemplateRouteImport.update({
  id: '/api/dev/email/$template',
  path: '/api/dev/email/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIdUpdateIndexRoute =
  ManagerUsersIdUpdateIndexRouteImport.update({
    id: '/users/$id/update/',
    path: '/users/$id/update/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ApiTelemetryOtelV1TracesRoute =
  ApiTelemetryOtelV1TracesRouteImport.update({
    id: '/api/telemetry/otel/v1/traces',
    path: '/api/telemetry/otel/v1/traces',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryOtelV1MetricsRoute =
  ApiTelemetryOtelV1MetricsRouteImport.update({
    id: '/api/telemetry/otel/v1/metrics',
    path: '/api/telemetry/otel/v1/metrics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/daily-ingest': typeof ApiCronDailyIngestRoute
  '/api/cron/weekly-reports': typeof ApiCronWeeklyReportsRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/manager/workspaces/': typeof ManagerWorkspacesIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/providers/$provider/callback': typeof ApiProvidersProviderCallbackRoute
  '/app/reports/$reportId/': typeof AppReportsReportIdIndexRoute
  '/app/sources/$sourceId/': typeof AppSourcesSourceIdIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/manager/workspaces/$id/': typeof ManagerWorkspacesIdIndexRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/daily-ingest': typeof ApiCronDailyIngestRoute
  '/api/cron/weekly-reports': typeof ApiCronWeeklyReportsRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/app/account': typeof AppAccountIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/manager/account': typeof ManagerAccountIndexRoute
  '/manager/dashboard': typeof ManagerDashboardIndexRoute
  '/manager/users': typeof ManagerUsersIndexRoute
  '/manager/workspaces': typeof ManagerWorkspacesIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/providers/$provider/callback': typeof ApiProvidersProviderCallbackRoute
  '/app/reports/$reportId': typeof AppReportsReportIdIndexRoute
  '/app/sources/$sourceId': typeof AppSourcesSourceIdIndexRoute
  '/manager/users/$id': typeof ManagerUsersIdIndexRoute
  '/manager/users/new': typeof ManagerUsersNewIndexRoute
  '/manager/workspaces/$id': typeof ManagerWorkspacesIdIndexRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
  '/manager/users/$id/update': typeof ManagerUsersIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/daily-ingest': typeof ApiCronDailyIngestRoute
  '/api/cron/weekly-reports': typeof ApiCronWeeklyReportsRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/manager/workspaces/': typeof ManagerWorkspacesIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/providers/$provider/callback': typeof ApiProvidersProviderCallbackRoute
  '/app/reports/$reportId/': typeof AppReportsReportIdIndexRoute
  '/app/sources/$sourceId/': typeof AppSourcesSourceIdIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/manager/workspaces/$id/': typeof ManagerWorkspacesIdIndexRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/onboarding'
    | '/logout'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/api/cron/daily-ingest'
    | '/api/cron/weekly-reports'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/api/webhooks/resend'
    | '/app/account/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/dashboard/'
    | '/manager/users/'
    | '/manager/workspaces/'
    | '/api/dev/email/$template'
    | '/api/providers/$provider/callback'
    | '/app/reports/$reportId/'
    | '/app/sources/$sourceId/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/manager/workspaces/$id/'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
    | '/manager/users/$id/update/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/app'
    | '/login'
    | '/manager'
    | '/onboarding'
    | '/api/auth/$'
    | '/api/cron/daily-ingest'
    | '/api/cron/weekly-reports'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/api/webhooks/resend'
    | '/app/account'
    | '/login/error'
    | '/login/verify'
    | '/manager/account'
    | '/manager/dashboard'
    | '/manager/users'
    | '/manager/workspaces'
    | '/api/dev/email/$template'
    | '/api/providers/$provider/callback'
    | '/app/reports/$reportId'
    | '/app/sources/$sourceId'
    | '/manager/users/$id'
    | '/manager/users/new'
    | '/manager/workspaces/$id'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
    | '/manager/users/$id/update'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/onboarding'
    | '/logout'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/api/cron/daily-ingest'
    | '/api/cron/weekly-reports'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/api/webhooks/resend'
    | '/app/account/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/dashboard/'
    | '/manager/users/'
    | '/manager/workspaces/'
    | '/api/dev/email/$template'
    | '/api/providers/$provider/callback'
    | '/app/reports/$reportId/'
    | '/app/sources/$sourceId/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/manager/workspaces/$id/'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
    | '/manager/users/$id/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDailyIngestRoute: typeof ApiCronDailyIngestRoute
  ApiCronWeeklyReportsRoute: typeof ApiCronWeeklyReportsRoute
  ApiTelemetryLogsRoute: typeof ApiTelemetryLogsRoute
  ApiTelemetrySentryTunnelRoute: typeof ApiTelemetrySentryTunnelRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiDevEmailTemplateRoute: typeof ApiDevEmailTemplateRoute
  ApiProvidersProviderCallbackRoute: typeof ApiProvidersProviderCallbackRoute
  ApiTelemetryOtelV1MetricsRoute: typeof ApiTelemetryOtelV1MetricsRoute
  ApiTelemetryOtelV1TracesRoute: typeof ApiTelemetryOtelV1TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/manager/workspaces/': {
      id: '/manager/workspaces/'
      path: '/workspaces'
      fullPath: '/manager/workspaces/'
      preLoaderRoute: typeof ManagerWorkspacesIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/users/': {
      id: '/manager/users/'
      path: '/users'
      fullPath: '/manager/users/'
      preLoaderRoute: typeof ManagerUsersIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/dashboard/': {
      id: '/manager/dashboard/'
      path: '/dashboard'
      fullPath: '/manager/dashboard/'
      preLoaderRoute: typeof ManagerDashboardIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/account/': {
      id: '/manager/account/'
      path: '/account'
      fullPath: '/manager/account/'
      preLoaderRoute: typeof ManagerAccountIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/verify'
      fullPath: '/login/verify/'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/error/': {
      id: '/login/error/'
      path: '/error'
      fullPath: '/login/error/'
      preLoaderRoute: typeof LoginErrorIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/sentry-tunnel': {
      id: '/api/telemetry/sentry-tunnel'
      path: '/api/telemetry/sentry-tunnel'
      fullPath: '/api/telemetry/sentry-tunnel'
      preLoaderRoute: typeof ApiTelemetrySentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/logs': {
      id: '/api/telemetry/logs'
      path: '/api/telemetry/logs'
      fullPath: '/api/telemetry/logs'
      preLoaderRoute: typeof ApiTelemetryLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/weekly-reports': {
      id: '/api/cron/weekly-reports'
      path: '/api/cron/weekly-reports'
      fullPath: '/api/cron/weekly-reports'
      preLoaderRoute: typeof ApiCronWeeklyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-ingest': {
      id: '/api/cron/daily-ingest'
      path: '/api/cron/daily-ingest'
      fullPath: '/api/cron/daily-ingest'
      preLoaderRoute: typeof ApiCronDailyIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workspaces/$id/': {
      id: '/manager/workspaces/$id/'
      path: '/workspaces/$id'
      fullPath: '/manager/workspaces/$id/'
      preLoaderRoute: typeof ManagerWorkspacesIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/users/new/': {
      id: '/manager/users/new/'
      path: '/users/new'
      fullPath: '/manager/users/new/'
      preLoaderRoute: typeof ManagerUsersNewIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/users/$id/': {
      id: '/manager/users/$id/'
      path: '/users/$id'
      fullPath: '/manager/users/$id/'
      preLoaderRoute: typeof ManagerUsersIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/sources/$sourceId/': {
      id: '/app/sources/$sourceId/'
      path: '/sources/$sourceId'
      fullPath: '/app/sources/$sourceId/'
      preLoaderRoute: typeof AppSourcesSourceIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/$reportId/': {
      id: '/app/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/app/reports/$reportId/'
      preLoaderRoute: typeof AppReportsReportIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/providers/$provider/callback': {
      id: '/api/providers/$provider/callback'
      path: '/api/providers/$provider/callback'
      fullPath: '/api/providers/$provider/callback'
      preLoaderRoute: typeof ApiProvidersProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/email/$template': {
      id: '/api/dev/email/$template'
      path: '/api/dev/email/$template'
      fullPath: '/api/dev/email/$template'
      preLoaderRoute: typeof ApiDevEmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/$id/update/': {
      id: '/manager/users/$id/update/'
      path: '/users/$id/update'
      fullPath: '/manager/users/$id/update/'
      preLoaderRoute: typeof ManagerUsersIdUpdateIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/api/telemetry/otel/v1/traces': {
      id: '/api/telemetry/otel/v1/traces'
      path: '/api/telemetry/otel/v1/traces'
      fullPath: '/api/telemetry/otel/v1/traces'
      preLoaderRoute: typeof ApiTelemetryOtelV1TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/otel/v1/metrics': {
      id: '/api/telemetry/otel/v1/metrics'
      path: '/api/telemetry/otel/v1/metrics'
      fullPath: '/api/telemetry/otel/v1/metrics'
      preLoaderRoute: typeof ApiTelemetryOtelV1MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppReportsReportIdIndexRoute: typeof AppReportsReportIdIndexRoute
  AppSourcesSourceIdIndexRoute: typeof AppSourcesSourceIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppReportsReportIdIndexRoute: AppReportsReportIdIndexRoute,
  AppSourcesSourceIdIndexRoute: AppSourcesSourceIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerAccountIndexRoute: typeof ManagerAccountIndexRoute
  ManagerDashboardIndexRoute: typeof ManagerDashboardIndexRoute
  ManagerUsersIndexRoute: typeof ManagerUsersIndexRoute
  ManagerWorkspacesIndexRoute: typeof ManagerWorkspacesIndexRoute
  ManagerUsersIdIndexRoute: typeof ManagerUsersIdIndexRoute
  ManagerUsersNewIndexRoute: typeof ManagerUsersNewIndexRoute
  ManagerWorkspacesIdIndexRoute: typeof ManagerWorkspacesIdIndexRoute
  ManagerUsersIdUpdateIndexRoute: typeof ManagerUsersIdUpdateIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerAccountIndexRoute: ManagerAccountIndexRoute,
  ManagerDashboardIndexRoute: ManagerDashboardIndexRoute,
  ManagerUsersIndexRoute: ManagerUsersIndexRoute,
  ManagerWorkspacesIndexRoute: ManagerWorkspacesIndexRoute,
  ManagerUsersIdIndexRoute: ManagerUsersIdIndexRoute,
  ManagerUsersNewIndexRoute: ManagerUsersNewIndexRoute,
  ManagerWorkspacesIdIndexRoute: ManagerWorkspacesIdIndexRoute,
  ManagerUsersIdUpdateIndexRoute: ManagerUsersIdUpdateIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDailyIngestRoute: ApiCronDailyIngestRoute,
  ApiCronWeeklyReportsRoute: ApiCronWeeklyReportsRoute,
  ApiTelemetryLogsRoute: ApiTelemetryLogsRoute,
  ApiTelemetrySentryTunnelRoute: ApiTelemetrySentryTunnelRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiDevEmailTemplateRoute: ApiDevEmailTemplateRoute,
  ApiProvidersProviderCallbackRoute: ApiProvidersProviderCallbackRoute,
  ApiTelemetryOtelV1MetricsRoute: ApiTelemetryOtelV1MetricsRoute,
  ApiTelemetryOtelV1TracesRoute: ApiTelemetryOtelV1TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
